version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: swgemu:database
    hostname: swg_database
    container_name: swg_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=swgemu
      - MYSQL_USER=swgemu
      - MYSQL_PASSWORD=swgemu_password
    volumes:
      - mysql:/var/lib/mysql
    restart: always
  core3:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.core3
    image: swgemu:core3
    hostname: swg_server
    container_name: swg_server
    ports:
      - "44419:44419"
      - "44419:44419/udp"
      - "44453:44453"
      - "44453:44453/udp"
      - "44462:44462"
      - "44462:44462/udp"
      - "44463:44463"
      - "44463:44463/udp"
      - "44455:44455"
      - "44455:44455/udp"
      - "44460:44460"
    volumes:
      - ./core3:/core3
      - ./conf:/core3/MMOCoreORB/bin/conf
      - ./tre:/tre
      - log:/core3/MMOCoreORB/bin/log
      - navmeshes:/core3/MMOCoreORB/bin/navmeshes
      - database:/core3/MMOCoreORB/bin/databases
    stop_grace_period: 1m
    restart: always
    stdin_open: true
    tty: true

volumes:
  mysql:
  database:
  navmeshes:
  log:
